add article Comments
obodev/obodev.github.io pull request #11
Opened 2022-12-03 09:59 UTC by AlexZhyg

add article Comments

2022-12-03 17:39 UTC, obozhdi requested changes

2022-12-03 17:39 UTC, obozhdi commented on all_collections/_posts/2022-12-01-comment.md
> +# Комментарии (Comments)
Я думаю, что можно доработать этот пейдж, написать про экранирование символов.

2022-12-04 04:33 UTC, AlexZhyg commented on all_collections/_posts/2022-12-01-comment.md
> +# Комментарии (Comments)
Если это про 
"...
Управляющие последовательности
Строка может содержать специальные символы, которые называются управляющими последовательностями или эскейп-последовательностями. Основные из них:
\n: перевод на новую строку
\t: табуляция
\": кавычка
\\: обратный слеш
..."

то может вынести это в работу с типами String, Character?

2022-12-14 07:04 UTC, obozhdi commented on all_collections/_posts/2022-12-01-comment.md
> +# Комментарии (Comments)
Я писал исключительно про экранирование символов.

2023-01-05 19:08 UTC, merged